#!/usr/bin/env python3
"""Build agent-native adapter files from the registry."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict


ROOT = Path(__file__).resolve().parents[1]
INDEX_JSON = ROOT / "registry" / "index.json"

GENERATED_NOTICE = "Generated by `tools/build_agent_adapters.py`. Do not edit by hand."
ROUTER_SKILL_NAME = "hpc-skill-hub"
ROUTER_DESCRIPTION = (
    "Search and apply the HPC Skill Hub registry for HPC workflow help. Use when "
    "the user asks for HPC, Slurm, PBS, LSF, HTCondor, Grid Engine, scheduler "
    "triage, containers, modules, MPI, GPU, data movement, workflow engines, "
    "interactive sessions, site adapters, or adding and validating registry skills."
)


def load_index() -> Dict[str, Any]:
    with INDEX_JSON.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def ensure_final_newline(text: str) -> str:
    return text if text.endswith("\n") else text + "\n"


def build_agents_md(index: Dict[str, Any]) -> str:
    return f"""# HPC Skill Hub Agent Instructions

<!-- {GENERATED_NOTICE} -->

## Repository Role

HPC Skill Hub is a public, reviewable registry of reusable HPC workflow
skills. Treat this repository as a registry and compatibility contract, not as
an arbitrary script dump.

Current generated registry snapshot:

- Skills: {index['skill_count']}
- Collections: {index['collection_count']}
- Site adapters: {index['site_adapter_count']}
- Registry schema version: `{index['schema_version']}`

## Fast Orientation

- Prefer `registry/index.json` for discovery and filtering.
- Use `skills/<skill-id>/README.md` and `skills/<skill-id>/examples/` for the
  full human-readable workflow before recommending commands.
- Use `site-adapters/*/site.json` only for public local policy mappings. Do not
  invent cluster-specific account, partition, module, filesystem, or hostname
  details.
- Use `docs/INTEGRATION_GUIDE.md`, `docs/SAFETY_MODEL.md`, and
  `docs/SKILL_SPEC.md` when changing integration behavior.

## Useful Commands

- List skills: `python3 tools/hpc_skill.py list`
- Search skills: `python3 tools/hpc_skill.py search <query> --json`
- Show a skill: `python3 tools/hpc_skill.py show <skill-id> --examples --json`
- Show collections: `python3 tools/hpc_skill.py collections --json`
- Validate one skill: `python3 tools/hpc_skill.py check <skill-id> --json`
- Validate the registry: `python3 tools/hpc_skill.py validate --json`
- Full local gate: `make check`

## Agent Integration

- Codex should use `.agents/skills/hpc-skill-hub/SKILL.md` for registry-backed
  HPC guidance.
- Claude Code should use `CLAUDE.md` plus `.claude/skills/hpc-skill-hub/SKILL.md`.
- Keep provider-specific generated files synchronized with:
  `python3 tools/build_agent_adapters.py`.
- Check generated agent files without writing with:
  `python3 tools/build_agent_adapters.py --check`.

## Safety Rules

- Do not execute example scripts automatically. Present commands for review,
  adapt placeholders, and require explicit user intent before real work.
- Before suggesting a command, show the skill id, version, maturity, risk level,
  source README, and relevant examples.
- Prefer read-only, dry-run, plan-only, static, or short smoke-test examples
  before any command that submits jobs, moves data, installs software, launches
  containers, opens tunnels, or consumes GPU allocations.
- Keep private cluster details, hostnames, usernames, allocation names, tokens,
  internal project ids, and unpublished security procedures out of prompts,
  examples, generated docs, logs, and public issues.
- Treat `maturity: seed` and `status: draft` as review signals, not production
  guarantees.

## Editing Guidance

- Keep generated artifacts deterministic. Update the generating script instead
  of hand-editing generated outputs.
- New skills should start with `python3 tools/hpc_skill.py scaffold skill`.
- After changing skills, collections, site adapters, schemas, generated docs, or
  agent adapters, run the narrow relevant check and then `make check` when
  practical.

## Review Guidelines

- Prioritize correctness, safety, public-reviewability, and missing validation.
- Verify that any recommended HPC action has clear cost, resource, and rollback
  or cleanup implications.
- Flag undocumented schema changes, stale generated files, hidden local policy,
  or examples that can perform expensive or destructive work without opt-in.
"""


def build_claude_md() -> str:
    return f"""@AGENTS.md

<!-- {GENERATED_NOTICE} -->

## Claude Code

- Use `/hpc-skill-hub` for HPC Skill Hub registry discovery, recommendation,
  authoring, validation, and safety-review tasks.
- Keep personal project notes in `CLAUDE.local.md`; do not commit that file.
- If a task needs provider-specific behavior, keep it below this section so the
  shared `AGENTS.md` guidance stays usable by other coding agents.
"""


def build_router_skill(provider: str) -> str:
    invocation = "$hpc-skill-hub" if provider == "codex" else "/hpc-skill-hub"
    provider_name = "Codex" if provider == "codex" else "Claude Code"
    return f"""---
name: {ROUTER_SKILL_NAME}
description: {ROUTER_DESCRIPTION}
---

# HPC Skill Hub Router

Use this skill to route {provider_name} through the repository registry instead
of guessing HPC guidance from memory. Invoke it explicitly as `{invocation}` or
use it implicitly when the user asks for HPC workflow help.

## Workflow

1. Identify whether the task is discovery, user guidance, skill authoring,
   registry validation, site-adapter work, or release/integration maintenance.
2. Search the registry with the narrowest useful query:
   `python3 tools/hpc_skill.py search <query> --json`.
3. Filter by `--scheduler`, `--category`, `--tool`, `--risk`, `--maturity`,
   `--status`, or `--collection` when the user gives enough context.
4. Inspect the selected skill with:
   `python3 tools/hpc_skill.py show <skill-id> --examples --json`.
5. Read the selected `skills/<skill-id>/README.md` and relevant example files
   before recommending commands or edits.
6. If local policy matters, inspect site adapters with
   `python3 tools/hpc_skill.py adapters --json` and
   `python3 tools/hpc_skill.py adapter <adapter-id> --json`. Ask the user for
   missing scheduler, account, partition, storage, module, or container values.
7. In the final answer, cite the skill id, version, maturity, risk level,
   README path, and example path used.

## Safety

- Prefer read-only, dry-run, plan-only, static, or short smoke-test examples.
- Do not submit jobs, move data, install software, launch containers, open
  tunnels, consume GPU allocations, or change shared-system state unless the
  user explicitly asks for that action after seeing the risk and assumptions.
- Preserve placeholders such as `<account>`, `<partition>`, `<project>`,
  `<cluster>`, `<user>`, and `<collection-id>` until the user supplies public
  or task-local values.
- Do not put private hostnames, usernames, allocation names, internal project
  ids, tokens, or unpublished operational details into public files.
- Treat draft and seed skills as starting points that require review.

## Authoring And Maintenance

- Create a new registry skill with
  `python3 tools/hpc_skill.py scaffold skill <skill-id> --category <category>`.
- Validate one skill with `python3 tools/hpc_skill.py check <skill-id> --json`.
- Validate generated agent adapters with
  `python3 tools/build_agent_adapters.py --check`.
- After changing registry metadata or examples, run the narrow validator first,
  then `make check` when practical.

## Output Shape

Use this compact evidence block when recommending a skill:

```text
Source: <skill-id> v<version>
Maturity: <maturity>
Risk: <risk_level>
README: skills/<skill-id>/README.md
Examples: skills/<skill-id>/examples/<file>
```
"""


def build_openai_yaml() -> str:
    return """interface:
  display_name: "HPC Skill Hub"
  short_description: "Find safe HPC workflow skills"
  default_prompt: "Use $hpc-skill-hub to find the safest HPC Skill Hub guidance for my workflow."

policy:
  allow_implicit_invocation: true
"""


def build_agent_integration_doc(index: Dict[str, Any]) -> str:
    return f"""# Agent Integration

<!-- {GENERATED_NOTICE} -->

This document explains how coding agents should consume HPC Skill Hub without
scraping prose or guessing cluster policy.

## Generated Agent Surfaces

| Surface | Consumer | Purpose |
| --- | --- | --- |
| `AGENTS.md` | Codex and AGENTS-aware coding agents | Shared repository instructions, safety rules, and validation commands. |
| `CLAUDE.md` | Claude Code | Imports `AGENTS.md` and adds Claude-specific invocation notes. |
| `.agents/skills/hpc-skill-hub/SKILL.md` | Codex | Router skill for registry-backed HPC guidance. |
| `.agents/skills/hpc-skill-hub/agents/openai.yaml` | Codex app | UI metadata and invocation policy for the router skill. |
| `.claude/skills/hpc-skill-hub/SKILL.md` | Claude Code | Router skill exposed as `/hpc-skill-hub`. |

The current generated registry snapshot contains {index['skill_count']} skills,
{index['collection_count']} collections, and {index['site_adapter_count']} site
adapters.

## How Agents Should Use The Registry

1. Search `registry/index.json` through `python3 tools/hpc_skill.py search`.
2. Show the user candidate skill ids with risk and maturity.
3. Inspect the selected skill with `python3 tools/hpc_skill.py show --examples`.
4. Read the selected README and examples before recommending commands.
5. Use site adapters only when public local policy exists.
6. Ask the user to confirm missing scheduler, account, partition, module,
   storage, container, and allocation assumptions.

Agents should cite the skill id, version, maturity, risk level, README path, and
example paths used for a recommendation.

## Safety Contract

Agents must not execute example commands automatically. They should present
commands for review, preserve placeholders until the user supplies values, and
prefer dry-run, read-only, plan-only, static, or short smoke-test examples.

Require explicit user intent before recommending or running actions that submit
jobs, move data, install software, launch containers, open tunnels, consume GPU
allocations, or change shared-system state.

Private hostnames, usernames, allocation names, tokens, internal project ids,
and unpublished security procedures do not belong in prompts, logs, examples,
generated docs, site adapters, or public issues.

## Maintaining The Adapters

Regenerate agent-facing files after changing the registry contract, safety
model, CLI commands, or provider integration behavior:

```bash
python3 tools/build_agent_adapters.py
```

Check freshness without writing files:

```bash
python3 tools/build_agent_adapters.py --check
```

The `agent-adapters` make target runs the same check and is part of
`make check`.

## Next Integration Step

The next layer should be a read-only MCP server over the same registry contract.
Start with tools such as `search_skills`, `show_skill`, `list_collections`,
`show_site_adapters`, and `validate_registry`. Keep write, submit, transfer,
and install actions out of the first MCP version.
"""


def build_outputs(index: Dict[str, Any]) -> Dict[Path, str]:
    return {
        ROOT / "AGENTS.md": build_agents_md(index),
        ROOT / "CLAUDE.md": build_claude_md(),
        ROOT / ".agents" / "skills" / ROUTER_SKILL_NAME / "SKILL.md": build_router_skill(
            "codex"
        ),
        ROOT
        / ".agents"
        / "skills"
        / ROUTER_SKILL_NAME
        / "agents"
        / "openai.yaml": build_openai_yaml(),
        ROOT / ".claude" / "skills" / ROUTER_SKILL_NAME / "SKILL.md": build_router_skill(
            "claude"
        ),
        ROOT / "docs" / "AGENT_INTEGRATION.md": build_agent_integration_doc(index),
    }


def write_or_check(path: Path, text: str, check: bool) -> bool:
    expected = ensure_final_newline(text)
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == expected:
        return False
    if check:
        rel_path = path.relative_to(ROOT)
        if current is None:
            print(f"missing generated file: {rel_path}", file=sys.stderr)
        else:
            print(f"out of date generated file: {rel_path}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Build coding-agent adapter files")
    parser.add_argument("--check", action="store_true", help="Check generated files")
    args = parser.parse_args()

    index = load_index()
    changed = False
    for path, text in build_outputs(index).items():
        changed = write_or_check(path, text, args.check) or changed

    if args.check and changed:
        return 1
    if args.check:
        print("Agent adapter files are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
