#!/usr/bin/env python3
"""Generate Codex and Claude Code MCP onboarding examples from one contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from hpc_skill_hub.client_contract import load_client_contract  # noqa: E402


GENERATED_NOTICE = (
    "Generated by `tools/build_mcp_client_configs.py` from "
    "`integrations/mcp-client.json`. Do not edit by hand."
)


def build_codex_config(contract: Dict[str, Any]) -> str:
    server = contract["server"]
    return f"""# {GENERATED_NOTICE}
# Review before merging into .codex/config.toml or ~/.codex/config.toml.

[mcp_servers.{server['id']}]
command = {json.dumps(server['command'])}
args = {json.dumps(server['args'])}
enabled = true
required = false
startup_timeout_sec = 15
tool_timeout_sec = 60
"""


def build_claude_config(contract: Dict[str, Any]) -> str:
    server = contract["server"]
    payload = {
        "mcpServers": {
            server["id"]: {
                "type": server["transport"],
                "command": server["command"],
                "args": server["args"],
                "env": server["env"],
            }
        }
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def command_block(commands: list[str]) -> str:
    return "\n".join(commands)


def build_setup_doc(contract: Dict[str, Any]) -> str:
    server = contract["server"]
    codex = contract["providers"]["codex"]
    claude = contract["providers"]["claude-code"]
    tool_list = ", ".join(f"`{name}`" for name in server["tools"])
    resource = server["resources"][0]
    return f"""# MCP Client Setup

<!-- {GENERATED_NOTICE} -->

HPC Skill Hub exposes a local, read-only stdio MCP server for Codex, Claude
Code, and compatible clients. The generated examples contain no credentials,
private cluster values, network listeners, or operational HPC tools.

## Install And Diagnose

Python {server['python']['mcp_minimum']} or later is required for the optional
MCP integration. Install it and run the local compatibility checks:

```bash
python3 -m pip install '{server['package_extra']}'
hpc-skill doctor --require-mcp
```

The doctor validates Python and dependency compatibility, packaged registry
data, registry schema {server['registry_schema_version']}, verified context digests,
the canonical client contract, and the exact in-memory MCP capability surface.
It does not execute skill examples or connect to a remote service.

## Codex

Add the server to the Codex user configuration:

```bash
{codex['add_command']}
{command_block(codex['verify_commands'])}
```

For a trusted repository-level configuration, review
`{codex['example_path']}` and merge its server table into
`{codex['project_config_path']}`. Codex CLI, IDE, and desktop surfaces share the
same configuration. The user-level path is `{codex['user_config_path']}`.

Official client reference: [{codex['documentation_url']}]({codex['documentation_url']})

## Claude Code

Add a shared project-scoped server:

```bash
{claude['add_command']}
{command_block(claude['verify_commands'])}
```

The project command writes `{claude['project_config_path']}`. Claude Code asks
each user to approve project-scoped MCP servers before first use. Review
`{claude['example_path']}` before adopting it; keep credentials and private site
policy out of version control. User-scoped configuration lives in
`{claude['user_config_path']}`.

Official client reference: [{claude['documentation_url']}]({claude['documentation_url']})

## Capability Boundary

The server exposes six tools: {tool_list}. It also exposes the
`{resource['name']}` resource at `{resource['uri_template']}` with MIME type
`{resource['mime_type']}`.

Every tool is read-only, non-destructive, idempotent, and closed-world. MCP
annotations are client hints; the server enforces the boundary by registering
only these named capabilities. Skill content is instructional context, not
authorization to submit jobs, move data, install software, launch containers,
open tunnels, or consume allocations.

## Updating Generated Files

Change `integrations/mcp-client.json`, then regenerate and validate:

```bash
python3 tools/build_mcp_client_configs.py
python3 tools/build_package_data.py
python3 tools/build_mcp_client_configs.py --check
hpc-skill doctor --require-mcp
```
"""


def outputs(contract: Dict[str, Any]) -> Dict[Path, str]:
    providers = contract["providers"]
    return {
        ROOT / providers["codex"]["example_path"]: build_codex_config(contract),
        ROOT / providers["claude-code"]["example_path"]: build_claude_config(contract),
        ROOT / "docs" / "MCP_CLIENT_SETUP.md": build_setup_doc(contract),
    }


def ensure_final_newline(text: str) -> str:
    return text if text.endswith("\n") else text + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> bool:
    expected = ensure_final_newline(expected)
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == expected:
        return False
    if check:
        state = "missing" if current is None else "out of date"
        print(f"{state} generated file: {path.relative_to(ROOT)}", file=sys.stderr)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build MCP client configuration examples from one contract"
    )
    parser.add_argument("--check", action="store_true", help="Check generated files")
    args = parser.parse_args()

    contract = load_client_contract()
    changed = False
    for path, expected in outputs(contract).items():
        changed = write_or_check(path, expected, args.check) or changed
    if args.check and changed:
        return 1
    if args.check:
        print("MCP client configuration examples are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
